"""Initial keywords related to Bank Indonesia KPwBI Aceh."""

DEFAULT_KEYWORDS = [
    ("Bank Indonesia Aceh", "institusi"),
    ("Bank Indonesia", "institusi"),
    ("BI Aceh", "institusi"),
    ("BI Banda Aceh", "institusi"),
    ("Kantor Perwakilan Bank Indonesia Provinsi Aceh", "institusi"),
    ("KPwBI Aceh", "institusi"),
    ("@bank_indonesia", "institusi"),
    ("Aceh", "wilayah"),
    ("Banda Aceh", "wilayah"),
    ("QRIS Aceh", "pembayaran"),
    ("QRIS Banda Aceh", "pembayaran"),
    ("QRIS", "pembayaran"),
    ("sistem pembayaran", "pembayaran"),
    ("BI-FAST", "pembayaran"),
    ("inflasi Aceh", "makro"),
    ("inflasi", "makro"),
    ("TPID Aceh", "makro"),
    ("ekonomi Aceh", "makro"),
    ("suku bunga", "makro"),
    ("BI-Rate", "makro"),
    ("UMKM Aceh", "umkm"),
    ("UMKM naik kelas", "umkm"),
    ("UMKM go digital", "umkm"),
    ("ekonomi syariah Aceh", "syariah"),
    ("keuangan syariah Aceh", "syariah"),
    ("halal Aceh", "syariah"),
    ("digitalisasi Aceh", "digital"),
    ("ekonomi kreatif Aceh", "umkm"),
    ("pariwisata Aceh", "makro"),
    ("Meuseuraya", "program"),
    ("TP2DD Aceh", "program"),
    ("ETPD Aceh", "program"),
    ("Cinta Bangga Paham Rupiah", "program"),
    ("CBPR", "program"),
    ("rupiah", "mata_uang"),
    ("uang rupiah", "mata_uang"),
    ("Bangga Buatan Indonesia", "program"),
]

STOPWORDS_ID = {
    "yang", "dan", "di", "ke", "dari", "ini", "itu", "dengan", "untuk",
    "pada", "adalah", "atau", "juga", "akan", "ada", "dalam", "tidak",
    "sudah", "bisa", "oleh", "karena", "sebagai", "lebih", "sangat",
    "mereka", "kami", "kita", "anda", "saya", "nya", "lah", "kah",
    "pun", "the", "a", "an", "of", "to", "in", "is", "are", "was",
    "bagi", "atas", "antara", "serta", "namun", "tetapi", "jika",
    "agar", "bahwa", "hal", "tahun", "hari", "bulan", "saat", "telah",
    "masih", "dapat", "para", "satu", "dua", "tiga", "baik", "baru",
}
