"""Initial keywords related to Bank Indonesia KPwBI Bali."""

DEFAULT_KEYWORDS = [
    ("Bank Indonesia Bali", "institusi"),
    ("Bank Indonesia", "institusi"),
    ("BI Bali", "institusi"),
    ("Kantor Perwakilan Bank Indonesia Provinsi Bali", "institusi"),
    ("KPwBI Bali", "institusi"),
    ("@bank_indonesia", "institusi"),
    ("Achris Sarwani", "figur"),
    ("Erwin Soeriadimadja", "figur"),
    ("rupiah Bali", "mata_uang"),
    ("penukaran uang Bali", "mata_uang"),
    ("QRIS Bali", "pembayaran"),
    ("QRIS Run", "pembayaran"),
    ("QRIS", "pembayaran"),
    ("GPIPS", "pembayaran"),
    ("GPIB", "pembayaran"),
    ("sistem pembayaran", "pembayaran"),
    ("inflasi Bali", "makro"),
    ("inflasi", "makro"),
    ("suku bunga", "makro"),
    ("BI-Rate", "makro"),
    ("SERAMBI Bank Indonesia", "program"),
    ("Baligivation", "program"),
    ("Bali Investment Challenge", "program"),
    ("Panca Kerti Bali", "program"),
    ("UMKM ekspor Bali", "umkm"),
    ("UMKM Bali", "umkm"),
    ("sistem pembayaran Bali", "pembayaran"),
    ("kurs Bali", "makro"),
    ("KUPVA Bali", "mata_uang"),
    ("ekonomi Bali pariwisata", "makro"),
    ("uang rupiah", "mata_uang"),
]

STOPWORDS_ID = {
    "yang", "dan", "di", "ke", "dari", "ini", "itu", "dengan", "untuk",
    "pada", "adalah", "atau", "juga", "akan", "ada", "dalam", "tidak",
    "sudah", "bisa", "oleh", "karena", "sebagai", "lebih", "sangat",
    "mereka", "kami", "kita", "anda", "saya", "nya", "lah", "kah",
    "pun", "the", "a", "an", "of", "to", "in", "is", "are", "was",
    "bagi", "atas", "antara", "serta", "namun", "tetapi", "jika",
    "agar", "bahwa", "hal", "tahun", "hari", "bulan", "saat", "telah",
    "masih", "dapat", "para", "satu", "dua", "tiga", "baik", "baru",
}
